apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
  name: flask
spec:
  replicas: 3  # Desired state: keep 3 pods alive
  selector:
    matchLabels:  # The pods I manage are the ones labeled app=flask
      app: flask
  strategy: {}
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: flaskapp:4.0
        name: flask
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: flask-config
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
        volumeMounts:
          - name: config-files
            mountPath: /etc/flask-config
      volumes:
        - name: config-files
          configMap:
            name: flask-config
