apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask
    spec:
      containers:
      - name: flask
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: GREETING
          value: {{ .Values.greeting | quote }}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet: { path: /healthz, port: 5000 }